#! /usr/bin/env ruby

platform = [ :cpu, :os ].map { |m| Gem::Platform.local.send(m) }
if platform[0] == "x86_64"
  platform[0] = "amd64"
end
PLATFORM = platform.join("-")

EXECUTABLE = File.expand_path(File.join(__dir__, PLATFORM, "thrust"))

if File.exist?(EXECUTABLE)
  exec(EXECUTABLE, *ARGV)
else
  STDERR.puts("ERROR: Unsupported platform: #{PLATFORM}")
  exit 1
end
