source "https://rubygems.org"

# Specify your gem's dependencies in thruster.gemspec.
gemspec

# Dummy app server
gem "puma"
gem "sqlite3"
gem "image_processing"
gem "ruby-vips"

# Formatting
gem "rubocop-rails-omakase", require: false
